# Generated by Django 3.1.2 on 2020-11-06 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antiplag', '0003_auto_20201106_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='text',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='user',
        ),
    ]
