# Generated by Django 3.1.2 on 2020-11-06 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("antiplag", "0004_auto_20201106_1008"),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="paper",
            name="title",
        ),
        migrations.AddField(
            model_name="paper",
            name="submission",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="antiplag.submission",
            ),
        ),
    ]
