# Generated by Django 3.1.2 on 2020-11-06 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("antiplag", "0005_auto_20201106_1221"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paper",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="antiplag.submission",
            ),
        ),
    ]
