# Generated by Django 3.1.2 on 2020-11-06 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antiplag', '0006_auto_20201106_1223'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paper',
        ),
    ]
