# Generated by Django 3.1.2 on 2020-11-06 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antiplag', '0009_auto_20201106_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binaryfile',
            name='submission',
        ),
        migrations.DeleteModel(
            name='Sub',
        ),
        migrations.DeleteModel(
            name='BinaryFile',
        ),
    ]
