# Generated by Django 3.1.3 on 2020-12-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("antiplag", "0003_auto_20201209_2040"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
