# Generated by Django 3.1.3 on 2020-12-13 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('antiplag', '0008_remove_result_error_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='antiplag.document'),
        ),
    ]
