# Generated by Django 3.1.3 on 2021-04-13 10:10

import antiplag.encoders
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("antiplag", "0014_migrate_uuid_foreign_keys"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="result",
            name="document",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="result",
                to="antiplag.document",
            ),
        ),
        migrations.AlterField(
            model_name="result",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="result",
            name="matched_docs",
            field=models.JSONField(encoder=antiplag.encoders.UUIDEncoder),
        ),
        migrations.AlterField(
            model_name="submission",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
